# Generated by Django 5.1.2 on 2024-12-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='hasMedia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='backgroundImage',
            field=models.ImageField(blank=True, default='post_images/background_pG2GYnu.jpg', null=True, upload_to='background_imgs'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(blank=True, default='post_images/Default_pfp-removebg-preview.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaURL',
            field=models.CharField(default='', max_length=255),
        ),
    ]
