# Generated by Django 5.1.2 on 2024-11-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(blank=True, default='post_images/Default_pfp-removebg-preview.png', null=True, upload_to='profile_pics'),
        ),
    ]
